In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
df = pd.read_csv("/Users/camilalopez/Downloads/icfes_resultados.csv")

# Verificar los valores únicos en cada columna categórica
for column in df:
    if column in df.columns:
        print(f"\nValores únicos en la columna '{column}':")
        print(df[column].unique())
    else:
        print(f"\nLa columna '{column}' no está presente en el DataFrame.")


Valores únicos en la columna 'periodo':
[20132 20122 20152 20172 20194 20142 20162 20102 20112 20211 20161 20224
 20131 20181 20141 20171 20121 20111 20201 20101 20151 20191 20221]

Valores únicos en la columna 'estu_tipodocumento':
['TI' 'CC' 'CR' 'PE' 'PC' 'PV' 'CE' 'NES' 'PEP' 'PPT' 'V' 'NUI' 'NIP' 'RC']

Valores únicos en la columna 'estu_consecutivo':
['SB11201320263257' 'SB11201220573699' 'SB11201320474163' ...
 'AC202210026617' 'AC202210022419' 'AC202210019245']

Valores únicos en la columna 'cole_area_ubicacion':
['URBANO' 'RURAL' nan]

Valores únicos en la columna 'cole_bilingue':
['N' nan 'S']

Valores únicos en la columna 'cole_calendario':
['A' 'OTRO' 'B']

Valores únicos en la columna 'cole_caracter':
['TÉCNICO/ACADÉMICO' 'ACADÉMICO' 'TÉCNICO' nan 'NO APLICA']

Valores únicos en la columna 'cole_cod_dane_establecimiento':
[1.25873000e+11 1.25754001e+11 4.25175033e+11 3.25899090e+11
 1.25307000e+11 2.25535000e+11 1.25754002e+11 2.25175000e+11
 2.25898800e+11 1.25754000e+11

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
df = pd.read_csv("/Users/camilalopez/Downloads/icfes_resultados.csv")

print(df.columns.tolist())
# Crear un diccionario de mapeo para las categorías
mapping = {
    'nan': 0,        # Valor nulo
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7': 7,
    '8': 8,
    '9': 9,
    '10 o más': 10.5,  # Valor promedio para '10 o más'
    '6 o más': 6.5     # Valor promedio para '6 o más'
}

# Crear un diccionario de mapeo para 'fami_educacionmadre'
mapping_madre = {
    'No Aplica': 0,
    'No sabe': 1,
    'Ninguno': 2,
    'Primaria incompleta': 3,
    'Primaria completa': 4,
    'Secundaria (Bachillerato) incompleta': 5,
    'Secundaria (Bachillerato) completa': 6,
    'Técnica o tecnológica incompleta': 7,
    'Técnica o tecnológica completa': 8,
    'Educación profesional incompleta': 9,
    'Educación profesional completa': 10,
    'Postgrado': 11
}

# Crear un diccionario de mapeo para 'fami_educacionpadre'
mapping_padre = {
    'No Aplica': 0,
    'No sabe': 1,
    'Ninguno': 2,
    'Primaria incompleta': 3,
    'Primaria completa': 4,
    'Secundaria (Bachillerato) incompleta': 5,
    'Secundaria (Bachillerato) completa': 6,
    'Técnica o tecnológica incompleta': 7,
    'Técnica o tecnológica completa': 8,
    'Educación profesional incompleta': 9,
    'Educación profesional completa': 10,
    'Postgrado': 11
}

# Mapeo para la codificación numérica de 'fami_cuartoshogar'
mapping_cuartoshogar = {
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7': 7,
    '8': 8,
    '9': 9,
    '10 o más': 10  # Consideramos '10 o más' como 10
}

# Aplicar el mapeo a la columna 'fami_cuartoshogar'
df['fami_cuartoshogar'] = df['fami_cuartoshogar'].map(mapping_cuartoshogar)


# Aplicar el mapeo a las columnas 'fami_educacionmadre' y 'fami_educacionpadre'
df['fami_educacionmadre'] = df['fami_educacionmadre'].map(mapping_madre)
df['fami_educacionpadre'] = df['fami_educacionpadre'].map(mapping_padre)

# Aplicar el mapeo a la columna 'fami_personashogar'
df['fami_personashogar'] = df['fami_personashogar'].map(mapping)

import pandas as pd

# Mapeo para las variables binarias
mapping_binario = {'No': 0, 'Si': 1}

# Aplicar el mapeo a las columnas correspondientes
df['fami_tienecomputador'] = df['fami_tienecomputador'].map(mapping_binario)
df['fami_tieneinternet'] = df['fami_tieneinternet'].map(mapping_binario)
df['fami_tienelavadora'] = df['fami_tienelavadora'].map(mapping_binario)
df['fami_tieneautomovil'] = df['fami_tieneautomovil'].map(mapping_binario)



['periodo', 'estu_tipodocumento', 'estu_consecutivo', 'cole_area_ubicacion', 'cole_bilingue', 'cole_calendario', 'cole_caracter', 'cole_cod_dane_establecimiento', 'cole_cod_dane_sede', 'cole_cod_depto_ubicacion', 'cole_cod_mcpio_ubicacion', 'cole_codigo_icfes', 'cole_depto_ubicacion', 'cole_genero', 'cole_jornada', 'cole_mcpio_ubicacion', 'cole_naturaleza', 'cole_nombre_establecimiento', 'cole_nombre_sede', 'cole_sede_principal', 'estu_cod_depto_presentacion', 'estu_cod_mcpio_presentacion', 'estu_cod_reside_depto', 'estu_cod_reside_mcpio', 'estu_depto_presentacion', 'estu_depto_reside', 'estu_estadoinvestigacion', 'estu_estudiante', 'estu_fechanacimiento', 'estu_genero', 'estu_mcpio_presentacion', 'estu_mcpio_reside', 'estu_nacionalidad', 'estu_pais_reside', 'estu_privado_libertad', 'fami_cuartoshogar', 'fami_educacionmadre', 'fami_educacionpadre', 'fami_estratovivienda', 'fami_personashogar', 'fami_tieneautomovil', 'fami_tienecomputador', 'fami_tieneinternet', 'fami_tienelavadora', 'd

In [3]:
variables_socioeconomicas = [col for col in df.columns if col.startswith('fami') or col == 'punt_lectura_critica']

df1 = df[variables_socioeconomicas]

df1.dropna(inplace=True)




/var/folders/wg/knznwbyd1250g3nq6hknkh8w0000gn/T/ipykernel_4401/3857323668.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.dropna(inplace=True)


In [4]:

# Verificar los valores únicos en cada columna categórica
for column in df1:
    if column in df1.columns:
        print(f"\nValores únicos en la columna '{column}':")
        print(df1[column].unique())
    else:
        print(f"\nLa columna '{column}' no está presente en el DataFrame.")



Valores únicos en la columna 'fami_cuartoshogar':
[ 2.  4.  1.  5.  7.  6.  9.  8. 10.]

Valores únicos en la columna 'fami_educacionmadre':
[ 5.  8.  6. 10.  3.  1.  4. 11.  9.  7.  2.]

Valores únicos en la columna 'fami_educacionpadre':
[ 6.  8. 10.  4.  9.  3.  5.  2. 11.  1.  7.]

Valores únicos en la columna 'fami_estratovivienda':
['2' '1' '3' '4' '5' '6']

Valores únicos en la columna 'fami_personashogar':
[3. 5. 4. 2. 6. 8. 7. 1. 9.]

Valores únicos en la columna 'fami_tieneautomovil':
[0. 1.]

Valores únicos en la columna 'fami_tienecomputador':
[0. 1.]

Valores únicos en la columna 'fami_tieneinternet':
[0. 1.]

Valores únicos en la columna 'fami_tienelavadora':
[0. 1.]

Valores únicos en la columna 'punt_lectura_critica':
[ 69.  50.  53.  62.  46.  47.  48.  51.  42.  44.  38.  57.  52.  29.
  63.  60.  67.  35.  56.  59.  72.  68.  32.  45.  54.  41.  43.  58.
  55.  33.  64.  78.  36.  49.  61.  31.  65.  30.  66.  75.  40.  70.
  85.  39.  77.  71.  84.  74.  26.  79.  

In [5]:
# Dividir los datos en características (X) y etiquetas (y)
X = df1

y = df1['punt_lectura_critica']


from sklearn.model_selection import train_test_split

# Dividir los datos en entrenamiento (80%) y prueba (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Dividir el conjunto de entrenamiento en entrenamiento (70%) y validación (30%)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.3, random_state=42)

# Ahora tienes X_train, y_train para el entrenamiento del modelo, X_val, y_val para la validación del modelo, y X_test, y_test para probar el modelo



In [6]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


# Normalizar los datos
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Convertir los datos a formato numpy
X_train_np = np.array(X_train, dtype=np.float32)
y_train_np = np.array(y_train, dtype=np.float32)
X_test_np = np.array(X_test, dtype=np.float32)
y_test_np = np.array(y_test, dtype=np.float32)

# Convertir los datos a tensores de PyTorch
X_train_tensor = torch.tensor(X_train_np, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train_np, dtype=torch.float32).unsqueeze(1)
X_test_tensor = torch.tensor(X_test_np, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test_np, dtype=torch.float32).unsqueeze(1)


# Definir el modelo de regresión utilizando PyTorch
class RegressionModel(nn.Module):
    def __init__(self, input_dim):
        super(RegressionModel, self).__init__()
        self.fc1 = nn.Linear(input_dim, 64)
        self.fc2 = nn.Linear(64, 64)
        self.fc3 = nn.Linear(64, 1)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# Crear una instancia del modelo
input_dim = X_train.shape[1]
model_regression = RegressionModel(input_dim)

# Definir la función de pérdida y el optimizador
criterion = nn.MSELoss()
optimizer = optim.Adam(model_regression.parameters(), lr=0.001)


# Entrenar el modelo
epochs = 50
batch_size = 32

for epoch in range(epochs):
    for i in range(0, len(X_train_tensor), batch_size):
        inputs = X_train_tensor[i:i+batch_size]
        labels = y_train_tensor[i:i+batch_size]

        optimizer.zero_grad()
        outputs = model_regression(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

    print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')


# Evaluar el modelo en el conjunto de prueba
with torch.no_grad():
    y_pred_tensor = model_regression(X_test_tensor)
    test_loss = criterion(y_pred_tensor, y_test_tensor)
    print("Mean Squared Error on Test Set:", test_loss.item())
    



Epoch [1/50], Loss: 1.1228
Epoch [2/50], Loss: 0.1338
Epoch [3/50], Loss: 0.1039
Epoch [4/50], Loss: 0.0285
Epoch [5/50], Loss: 0.0096
Epoch [6/50], Loss: 0.0074
Epoch [7/50], Loss: 0.0081
Epoch [8/50], Loss: 0.0035
Epoch [9/50], Loss: 0.0016
Epoch [10/50], Loss: 0.0011
Epoch [11/50], Loss: 0.0015
Epoch [12/50], Loss: 0.0021
Epoch [13/50], Loss: 0.0012
Epoch [14/50], Loss: 0.0015
Epoch [15/50], Loss: 0.0049
Epoch [16/50], Loss: 0.0055
Epoch [17/50], Loss: 0.0065
Epoch [18/50], Loss: 0.0086
Epoch [19/50], Loss: 0.0018
Epoch [20/50], Loss: 0.0043
Epoch [21/50], Loss: 0.0034
Epoch [22/50], Loss: 0.0037
Epoch [23/50], Loss: 0.0035
Epoch [24/50], Loss: 0.0017
Epoch [25/50], Loss: 0.0018
Epoch [26/50], Loss: 0.0025
Epoch [27/50], Loss: 0.0086
Epoch [28/50], Loss: 0.0005
Epoch [29/50], Loss: 0.0027
Epoch [30/50], Loss: 0.0010
Epoch [31/50], Loss: 0.0009
Epoch [32/50], Loss: 0.0015
Epoch [33/50], Loss: 0.0016
Epoch [34/50], Loss: 0.0016
Epoch [35/50], Loss: 0.0025
Epoch [36/50], Loss: 0.0021
E

In [7]:
from sklearn.metrics import mean_absolute_error, r2_score

# Convertir las predicciones y las etiquetas de PyTorch a numpy arrays
y_pred_np = y_pred_tensor.numpy()
y_test_np = y_test_tensor.numpy()

# Calcular el Mean Absolute Error (MAE)
mae = mean_absolute_error(y_test_np, y_pred_np)

# Calcular el R^2 Score
r2 = r2_score(y_test_np, y_pred_np)

print("Mean Squared Error on Test Set:", test_loss.item())
print("Mean Absolute Error on Test Set:", mae)
print("R^2 Score on Test Set:", r2)


Mean Squared Error on Test Set: 0.0019253656500950456
Mean Absolute Error on Test Set: 0.033707093
R^2 Score on Test Set: 0.9999775379579262


In [15]:
import joblib
import torch

# Guardar el estado del modelo
torch.save(model_regression.state_dict(), 'modelo_regresion.pth')

# Guardar el escalador
joblib.dump(scaler, 'scaler1.pkl')


['scaler1.pkl']

In [16]:
import joblib
import torch
from sklearn.preprocessing import StandardScaler

# Definir la clase RegressionModel (debe ser igual a la que usaste para entrenar)
class RegressionModel(nn.Module):
    def __init__(self, input_dim):
        super(RegressionModel, self).__init__()
        self.fc1 = nn.Linear(input_dim, 64)
        self.fc2 = nn.Linear(64, 64)
        self.fc3 = nn.Linear(64, 1)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# Cargar el escalador
scaler = joblib.load('scaler1.pkl')

# Crear una instancia del modelo
input_dim = X_train.shape[1]  # Debes definir X_train o conocer su dimensión
model_regression = RegressionModel(input_dim)

# Cargar el estado del modelo
model_regression.load_state_dict(torch.load('modelo_regresion.pth'))
model_regression.eval()  # Poner el modelo en modo de evaluación



# Evaluar el modelo en el conjunto de prueba
with torch.no_grad():
    y_pred_tensor = model_regression(X_test_tensor)
    test_loss = criterion(y_pred_tensor, y_test_tensor)
    print("Mean Squared Error on Test Set:", test_loss.item())


Mean Squared Error on Test Set: 0.0019253656500950456
